#!/usr/bin/python
# -*-coding:utf-8 -*-
#****************************************************
# Author: tony - birdaccp@gmail.com
# Create by: 2013-08-17 12:53
# Last modified: 2013-08-17 12:53
# Filename: test_api.py
# Description:
#****************************************************
import signal
import sys
def handler(signum, frame):
    print "use press ctrl+c exit"
    sys.exit(0)
signal.signal(signal.SIGINT, handler)

import os
import re
import urllib
from kuaipan import KuaipanAPI

consumer_key = 'xcr5NKAtWRtjWVOb'
consumer_secret = 'mPM0J4vn6gDu3oJG'

def main(consumer_key, consumer_secret, app_name, username, userpwd, url):
    api = KuaipanAPI(consumer_key, consumer_secret)

    api.requestToken()
    authorize_url = api.authorize()
    auth_code = api.get_auth_code(authorize_url)
    api.accessToken(auth_code)

    # print api.account_info()
    # print api.metadata(path="testupload")
    api.download_file("%2Ftestupload%2Frtmpserver.rst")
    # api.create_folder("testupload2")


if __name__ == "__main__":
    consumer_key = 'xcr5NKAtWRtjWVOb'
    consumer_secret = 'mPM0J4vn6gDu3oJG'
    app_name = 'fusekuaipan'
    username = ''
    userpwd = ''
    url = 'https://www.kuaipan.cn/api.php?ac=open&op=authorisecheck'
    account = main(consumer_key, consumer_secret, app_name, username, userpwd, url)
    #print account.user_name
    #import common
    #print common.random_string()
    #print os.popen()


